### PR TITLE
Add basic deal endpoints

### PR DESCRIPTION
**Pull request by jenssegers**

### CODE REVIEW

**Review by mrtus — APPROVED** [review]
Looks good 👍 

Only thing I am missing here is the deal phases & deal sources, which should probably follow shortly?

**Comment by mrtus** [comment]
@stivni @jenssegers the `for_attention_of` field was added

**Comment by WouterSioen** [comment]
@jenssegers can we get this merged? I can do some adjustments if needed.

**Review by JordyDeGroeve — APPROVED** [review]
Why is this put on hold?

**Review by WouterSioen — APPROVED** [review]

**Comment by WouterSioen** [comment]
@jenssegers I can believe this can be unblocked now?

**Pull request merged**
