### PR TITLE
Add documentation on web_url

### PR DESCRIPTION
**Pull request by tiagobastos**
Added _web_url_ on _companies_, _contacts_ and _deals_

Related to: [#195](https://github.com/teamleadercrm/api/pull/195)

### CODE REVIEW

**Review by tiagobastos — COMMENTED** [review]
Without the *`* around the word _web_url_ the output would appear misformatted. 
Anyone knows why?

**Comment by mrtus** [comment]
@tiagobastos What does it do without the url? Can you try that?

**Comment by mrtus** [comment]
@tiagobastos Could it be only a local issue? Can you give the endpoint `/invoices.download` a look where we also show a url? You can just remove the `` ` ``

**Comment by rathesDot** [comment]
I can reproduce the issue. The problem seems to be the underscore in the url, not in the underscore in `web_url` ...

In general, the `_` is a reserved character in MSON, so using backticks is fine here. https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords

**Comment by tiagobastos** [comment]
Actually, if only the key or the value has the underscore its fine. But both having it creates the misformatted output. So the backticks in both are the way to go, i think.

**Review by dietrichm — APPROVED** [review]

**Review by rathesDot — APPROVED** [review]
According to the definition of MSON, backticks should be added whenever we use reserved characters like _ ... SO this is fine here

**Review by paultimoce — APPROVED** [review]
looking good

**Pull request merged**
