### PR TITLE
[CAL-1492] Add task_id filter to events.list.

### PR DESCRIPTION
**Pull request by r1dotl**
Implementation: https://github.com/teamleadercrm/core/pull/10300

`task_id` filter was added to `/events.list`

### CODE REVIEW

**Review by WouterSioen — DISMISSED** [review]

**Review by mikeverf — DISMISSED** [review]

**Comment by jenssegers** [comment]
Can we use `todo_id` here?

**Comment by jenssegers** [comment]
The event object is returning a `todo`. So either we need to go for `todo_id` here or rename the `todo` to `task` in the response imo.

**Comment by r1dotl** [comment]
> The event object is returning a `todo`. So either we need to go for `todo_id` here or rename the `todo` to `task` in the response imo.

We are working on renaming everything to task instead of todo.

**Review by JorenSaey — DISMISSED** [review]

**Comment by psrpinto** [comment]
> The event object is returning a todo. So either we need to go for todo_id here or rename the todo to task in the response imo.

@jenssegers That's indeed our plan, we'll be renaming `todo` in the Event response to `task`, in the next API version.

**Comment by psrpinto** [comment]
conflicts 🚑

**Comment by jenssegers** [comment]
@regularjack Will this be released together with that rename? Because now it's going to become even more confusing having both task and todo in 1 endpoint.

**Comment by psrpinto** [comment]
@jenssegers The goal is to release the rename in the next version, 2019-07-03. We weren't planning on holding this PR until that version, but can do so if you think it's best. In that case, this PR would change to target branch `2019-07-03` instead of master.

**Comment by stivni** [comment]
Another solution might be to name the filter `todo` right now and change it together with the other BC break?

**Comment by psrpinto** [comment]
@stivni That would imply a BC-compatibility layer, so I'd prefer the simpler option of releasing this in version 2019-07-03.

@r1dotl what do you think? If you agree, we'd change the target branch of this to `2019-07-03`.

**Comment by r1dotl** [comment]
> @stivni That would imply a BC-compatibility layer, so I'd prefer the simpler option of releasing this in version 2019-07-03.
> 
> @r1dotl what do you think? If you agree, we'd change the target branch of this to `2019-07-03`.

I agree with releasing it with the 2019-07-03 version.

**Comment by r1dotl** [comment]
Closing this one and will open one based on 2019-07-03 branch.

**Pull request closed without merging**
