### PR TITLE
Add Money custom field

### PR DESCRIPTION
**Pull request by jenssegers**
When returning a monetary value in custom fields, it would be best to also return the currency of the account.

### CODE REVIEW

**Review by mrtus — APPROVED** [review]
Ah yes makes sense!

**Review by marijnvandevoorde — APPROVED** [review]

**Review by steftrenson — APPROVED** [review]

**Review by JordyDeGroeve — APPROVED** [review]

**Comment by WouterSioen** [comment]
I did put this on hold since it's not implemented like this yet.

**Review by WouterSioen — APPROVED** [review]

**Comment by WouterSioen** [comment]
@jenssegers I guess this should be changed for custom field values (when adding/updating entities with related custom fields too)?

Might be best to make a CustomFieldValue datastructure then?

**Review by dietrichm — APPROVED** [review]

**Comment by WouterSioen** [comment]
Talked this through with Jens and we thin it might be better to not pass the currency at the moment since you can't change it.

**Comment by jenssegers** [comment]
@WouterSioen Take the account currency for now.

**Review by jdrieghe — APPROVED** [review]

**Comment by WouterSioen** [comment]
Merged in master to fix linting.

**Comment by thomasnoe07** [comment]
@WouterSioen Should this PR stay open or can it be closed?

**Comment by WouterSioen** [comment]
We can't really do that anymore, right, since this would be a BC breaking change? @jenssegers

**Comment by stivni** [comment]
@jenssegers @dietrichm is this something we can pick up again?
I would actually like this, but if we don't find the time to implement this (BC) we should close this?

**Comment by JordyDeGroeve** [comment]
Any update on this?

**Comment by dietrichm** [comment]
Up to @jenssegers but I'd close this unless you deem this is in scope of some of the work you're going to pick up for the upcoming leap.

**Comment by jenssegers** [comment]
Will close. Looks like it won't be picked up in the roadmap any time soon.

**Pull request closed without merging**
