### PR TITLE
[CORE-864] Companies.list primary_address

### PR DESCRIPTION
**Pull request by JordyDeGroeve**
Update **companies.list** to show both `primary_address` and `address`.

### CODE REVIEW

**Review by jenssegers — DISMISSED** [review]

**Comment by WouterSioen** [comment]
Not sure if we should keep the address documented since we will remove it and don't want to let people use it anymore?

**Comment by JordyDeGroeve** [comment]
Wasn't sure if I should already remove it now or when we remove the implementation.
How do we handle these name chances in the docs, @jenssegers @stivni @mrnnn ?

**Review by WouterSioen — DISMISSED** [review]
Let's not keep deprecated features documented, otherwise people will expect them to stay available.

**Comment by jenssegers** [comment]
You're right @WouterSioen, let's remove it!

**Review by WouterSioen — APPROVED** [review]

**Review by mansilaxel — APPROVED** [review]

**Review by dietrichm — APPROVED** [review]

**Pull request merged**
