### PR TITLE
 Added custom_fields to products.info response

### PR DESCRIPTION
**Pull request by lasyan3**
Same as companies.info, invoices.info, etc.
Edit: also allow sorting invoices.list by invoice_date (second commit).

### CODE REVIEW

**Comment by joaoinacio** [comment]
Looks good to me, but the main `apiary.apib` file also needs to be updated (see `make`)

**Comment by marievandaele** [comment]
Feel free to send an email to support@teamleader.eu, asking to be linked  to issue ID-2833 (adding custom fields to product.info response) and ID-4653(filtering invoices.list on invoice_date). That way we'll update you once this has been added to our API

**Comment by lasyan3** [comment]
> 
> 
> Looks good to me, but the main `apiary.apib` file also needs to be updated (see `make`)

How am I supposed to do that? The documentation says to use Docker but a bit more explanations would be appreciated, thanks.

**Comment by Brammm** [comment]
Just came across this issue as well. Is there some way to get the custom field data for products through the API?

**Comment by mrtus** [comment]
@Brammm @lasyan3 Custom fields was made available, I will close this issue.

@lasyan3 sorting on `invoice_date` was made available.

As @marievandaele mentioned, any other requests, please send them to our support team who will take care of your request and link it to the matching tracking, once implemented you will be notified about these changes.

**Pull request closed without merging**
