### PR TITLE
[CORE-489] Add deals.move

### PR DESCRIPTION
**Pull request by JordyDeGroeve**
Add deals.move to api docs

### CODE REVIEW

**Review by WouterSioen — APPROVED** [review]

**Review by vanbrabantf — APPROVED** [review]

**Review by mrtus — APPROVED** [review]

**Comment by WouterSioen** [comment]
@jenssegers I guess this can be merged?

**Comment by WouterSioen** [comment]
Depends on a previous PR though

**Review by jenssegers — APPROVED** [review]

**Comment by WouterSioen** [comment]
@jenssegers @JordyDeGroeve This should've gone to master I guess?

**Comment by WouterSioen** [comment]
Opened a new PR for this now pointend to master https://github.com/teamleadercrm/api/pull/84

**Pull request merged**
