### PR TITLE
Invoiceability on timers and timetracking

### PR DESCRIPTION
**Pull request by JordyDeGroeve**

### CODE REVIEW

**Review by kevinwaelkens — APPROVED** [review]
bery gud

**Review by WouterSioen — APPROVED** [review]
💅

**Review by tiagobastos — APPROVED** [review]

**Review by dietrichm — APPROVED** [review]

**Comment by dietrichm** [comment]
✅ Checked

**Review by luisaterrabrito — APPROVED** [review]

**Comment by tiagobastos** [comment]
Shouldn't `project` be in the `subject type`?

**Review by jenssegers — APPROVED** [review]

**Review by mrtus — APPROVED** [review]

**Comment by JordyDeGroeve** [comment]
@tiagobastos I think it will be needed indeed. Will check this and eventually add the project if it's needed.

**Pull request merged**
