### PR TITLE
[PRO-2756] Custom fields on tasks

### PR DESCRIPTION
**Pull request by ketlane**
### Ticket
Link to ticket: https://teamleader.atlassian.net/browse/PRO-2756

E2E tests: https://github.com/teamleadercrm/api-tests/pull/877
Implementation:
https://github.com/teamleadercrm/core/pull/12766 (retrieve)
https://github.com/teamleadercrm/core/pull/12788 (retrieve follow-up)
https://github.com/teamleadercrm/core/pull/12768 (create/update)

### What has been done
- We're adding custom fields on tasks (tasks.info, tasks.create, tasks.update)

### CODE REVIEW

**Comment by ketlane** [comment]
Not sure whether we should add these custom fields to the list endpoint, or only to the info endpoint.

**Review by jenssegers — DISMISSED** [review]

**Comment by joaoinacio** [comment]
> Not sure whether we should add these custom fields to the list endpoint, or only to the info endpoint.

IMO only `.info`, but let's discuss it?

Also, since we're adding the custom fields to the `tasks.create` endpoint, maybe that can be documented at the same time/PR ?

**Comment by ketlane** [comment]
Updated the PR to only include custom fields on the .info endpoint, to remain consistent with the other endpoints that expose custom fields. Also documented the way to add / update custom fields.

**Review by adognameddog — APPROVED** [review]

**Review by jenssegers — APPROVED** [review]

**Review by joaoinacio — APPROVED** [review]

**Review by ArnaudWeyts — APPROVED** [review]

**Comment by adognameddog** [comment]
✅ Manually checked

**Pull request merged**
