### PR TITLE
Proposal for deals.report

### PR DESCRIPTION
**Pull request by lowiebenoot**
#### ⚠️  (@stivni told me to merge this into an integration branch instead of master because it's an internal endpoint for now).

Small note/request for feedback: I'm doubting a bit about the mixing of `phase` and `dealPhase`. What do you think?

### CODE REVIEW

**Comment by stivni** [comment]
> I'm doubting a bit about the mixing of phase and dealPhase. What do you think

I'm in doubt too... doesn't really matter... but maybe for consistency `dealPhase`?

**Comment by stivni** [comment]
During a discussion with @lowiebenoot , two thinks popped up in mind : 

- multicurrency : how does this influence how we report and visualize...
- limitedcrmaccess & limiteddealacces : how does this influence the whole feature and what we return in these endpoints...

some things to think about...

**Comment by lowiebenoot** [comment]
Any feedback @jenssegers?

**Review by jenssegers — APPROVED** [review]

**Comment by jenssegers** [comment]
I think `phase` is fine. We mainly name it `dealPhases` because `phases` alone could conflict with another domain. But when you're talking about deals I think it's fine to have just `phase`. It even fits the domain language much more than saying a deal has a deal-phase.

Similarly, I think a product has a `category` of the type `productCategory`.

**Review by Yarn-e — APPROVED** [review]

**Review by EOSullivanBerlin — APPROVED** [review]

**Review by stivni — APPROVED** [review]
I'd like to discuss the behaviour for limited crm- and limit deal-access, but that won't affect request/response format, so :shipit:

**Review by tiagobastos — APPROVED** [review]

**Review by luisaterrabrito — APPROVED** [review]

**Pull request merged**
