### PR TITLE
Add opted_in_for_mailings field for contacts and companies

### PR DESCRIPTION
**Pull request by WouterSioen**

### CODE REVIEW

**Review by JordyDeGroeve — DISMISSED** [review]

**Review by rathesDot — DISMISSED** [review]

**Review by dietrichm — CHANGES_REQUESTED** [review]
B: `apiary.apib` has not been rebuilt.

**Comment by WouterSioen** [comment]
Thanks @dietrichm 
We can probably verify this through CI though I guess? 🤔 (check if a build changes the apiary file)

**Review by dietrichm — APPROVED** [review]

**Comment by dietrichm** [comment]
Hmm, won't be that simple. A build may also only change some markdown files, `Makefile`, etc.

**Comment by JordyDeGroeve** [comment]
Can we prevent this by running the `build` command when a pr gets merged?

**Comment by WouterSioen** [comment]
Can we get some reviews here so this can be released? 🙏

**Review by JordyDeGroeve — APPROVED** [review]

**Review by rathesDot — APPROVED** [review]

**Pull request merged**
