### PR TITLE
Add quotation ids to deals.info endpoint

### PR DESCRIPTION
**Pull request by jdrieghe**
### Added
- `/deals.info` now also returns the ids of related quotations. For now this will be maximum one, but this can change in the future.

### CODE REVIEW

**Review by steftrenson — APPROVED** [review]
LGTM

**Review by jenssegers — APPROVED** [review]
🥇

**Review by lowiebenoot — APPROVED** [review]
Didn't know a deal could have multiple quotations, or is that something new?

**Comment by jdrieghe** [comment]
@lowiebenoot future proof

**Review by rathesDot — APPROVED** [review]

**Pull request merged**
