### PR TITLE
Add attendees to events.update

### PR DESCRIPTION
**Pull request by psrpinto**

### CODE REVIEW

**Review by jenssegers — DISMISSED** [review]

**Comment by psrpinto** [comment]
On hold since we still have to tackle side effects (tracking etc). Don't merge please.

**Review by WouterSioen — APPROVED** [review]

**Review by JordyDeGroeve — APPROVED** [review]

**Comment by psrpinto** [comment]
@WouterSioen @JordyDeGroeve @Jdww could you re-approve? Had to merge master

**Review by WouterSioen — APPROVED** [review]

**Review by WouterSioen — APPROVED** [review]

**Comment by WouterSioen** [comment]
I thought approves were not reset when merging in master? 🤔

**Review by Jdww — APPROVED** [review]

**Comment by psrpinto** [comment]
@WouterSioen Merging master (using the button here) doesn't always reset approves, I couldn't yet figure out what the rule is.

BTW @jenssegers, can we remove the need to "Update branch"? The PRs are always "outdated" which is super annoying since updating the branch resets approves.

**Review by WouterSioen — APPROVED** [review]
Agree that the need to have your branch up to date with master is super annoying on a project where multiple PR's will always be open at the same time

**Pull request merged**
