### PR TITLE
Rename address to primary_address in CRM info endpoints

### PR DESCRIPTION
**Pull request by jenssegers**

### CODE REVIEW

**Review by JordyDeGroeve — APPROVED** [review]

**Review by WouterSioen — COMMENTED** [review]
This is BC breaking, so not sure if we can safely do this? I can imagine some integrations/the app already using this?

Also: if we change it, couldn't we just return the array of addresses like in the `info` endpoints?

**Comment by mrtus** [comment]
Pretty sure `address` is clear enough? If there is only one address to be set why would it be anything other than the primary?

Also BC breaking..

**Review by marijnvandevoorde — APPROVED** [review]
Approving this, although this is of course a BC. So should we start talking about versioning now? Or do we still consider this ok since we're under 'beta' at the moment? If so, we should do this pronto before we're out of the beta phase @stivni

**Comment by marijnvandevoorde** [comment]
@WouterSioen, we found it gave too much overhead and in the end, if you need those addressed, there's the info endpoint.
@mrtus, it's just more explicit.

**Review by dietrichm — APPROVED** [review]

**Comment by marijnvandevoorde** [comment]
@jenssegers, please merge or destroy?

**Comment by WouterSioen** [comment]
Don't merge documentation without implementation please 😉 

I'd say "implement or destroy"

**Comment by marijnvandevoorde** [comment]
Very close, implementation happend here: https://github.com/teamleadercrm/core/pull/5069

When that's live, we can update docs.

**Review by JordyDeGroeve — COMMENTED** [review]
Damn, I totally forgot about this PR. 
Merged this yesterday: https://github.com/teamleadercrm/api/pull/132, so companies is already covered.
There is one for contacts too. Should I close that? https://github.com/teamleadercrm/api/pull/135

**Comment by JordyDeGroeve** [comment]
As discussed with @jenssegers, closed in favor of https://github.com/teamleadercrm/api/pull/132 and https://github.com/teamleadercrm/api/pull/135

**Pull request closed without merging**
