### PR TITLE
[TIDAL-2702] `departments.list` sorting options

### PR DESCRIPTION
**Pull request by adognameddog**

### CODE REVIEW

**Review by mrtus — DISMISSED** [review]

**Review by uhajzeraj — DISMISSED** [review]

**Review by lorgan3 — DISMISSED** [review]
Will probably be October when this is released though 😅

**Review by BrechtBonte — DISMISSED** [review]

**Review by jnstr — DISMISSED** [review]

**Review by driesd — DISMISSED** [review]

**Comment by BrechtBonte** [comment]
:heavy_check_mark: Lints and renders correctly

**Review by lorgan3 — APPROVED** [review]

**Review by jnstr — APPROVED** [review]

**Review by driesd — APPROVED** [review]

**Comment by monty241** [comment]
We are receiving user complaints that V2.Departments requires a filter since this morning. Is this an intentional change related to this commit or a bug?

> filter must not be empty (filter)
> Bad Request

**Comment by adognameddog** [comment]
> We are receiving user complaints that V2.Departments requires a filter since this morning. Is this an intentional change related to this commit or a bug?
> 
> > filter must not be empty (filter)
> > Bad Request

That is an unintentional change, which we will revert asap. Thank you very much for bringing it to our attention.

**Comment by monty241** [comment]
@adognameddog Thanks for the clear and swift answer! We will inform end users where relevant and ask them to try again later.

**Comment by adognameddog** [comment]
@monty241 This issue is fixed. `filter` is allowed to be empty again.

Thanks again for reporting this 🙌

**Comment by monty241** [comment]
Thanks for the quick resolution! Just two users were impacted.

**Pull request merged**
