### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by jenssegers**
Add changelog with breaking changes that will go live on 2018-05-15.

### CODE REVIEW

**Review by JordyDeGroeve — DISMISSED** [review]
👍

**Review by WouterSioen — DISMISSED** [review]

**Review by Brammm — APPROVED** [review]
Will this be versioned or are you just breaking the API at that point?

**Comment by jenssegers** [comment]
@Brammm Currently breaking. Will do versioning once we remove the beta label.

**Comment by Brammm** [comment]
Right, forgot about the beta label. g2g, @jenssegers !

**Review by jdrieghe — DISMISSED** [review]

**Pull request merged**
