### PR TITLE
Add ledger to invoices.info

### PR DESCRIPTION
**Pull request by luisaterrabrito**

### CODE REVIEW

**Review by JordyDeGroeve — DISMISSED** [review]

**Review by JordyDeGroeve — COMMENTED** [review]
Q: did you edit the apiary directly? Some changes are made in the apiary.apib but not in the seperate files themselve?

**Comment by luisaterrabrito** [comment]
Thanks, this makes no sense, I will amend the commit

**Comment by luisaterrabrito** [comment]
Now it is good, thank you @JordyDeGroeve

**Review by JordyDeGroeve — APPROVED** [review]

**Comment by luisaterrabrito** [comment]
This no longer applies, will open another PR

**Pull request closed without merging**
