### PR TITLE
Add fiscal_regime to department info

### PR DESCRIPTION
**Pull request by luisaterrabrito**

### CODE REVIEW

**Review by tiagobastos — DISMISSED** [review]

**Review by WouterSioen — DISMISSED** [review]

**Review by jdrieghe — DISMISSED** [review]

**Comment by luisaterrabrito** [comment]
Do we want to merge this? It is behind a feature flag.

**Comment by WouterSioen** [comment]
Only when the feature flag is fully rolled out I guess?

**Comment by WouterSioen** [comment]
It wouldn't make sense to document a feature that is not available for everyone.

**Review by JordyDeGroeve — DISMISSED** [review]

**Comment by dcsg** [comment]
@WouterSioen partially I agree with you but how are our integrators see the documentation to a feature that is not GA but they want to start implementing to have it ready when it goes GA?

**Comment by WouterSioen** [comment]
@dcsg contact them?

**Comment by dcsg** [comment]
@WouterSioen that might be an option, but I don't see why we cannot publish things in the API Docs that are behind a FF and explicitly say that is a beta feature only available upon request.

**Comment by WouterSioen** [comment]
You'll have to contact the integrators that want it anyway to let them know. I find it really weird to document behaviour that is not there for part of the users.

**Review by steftrenson — DISMISSED** [review]

**Review by steftrenson — APPROVED** [review]

**Review by jdrieghe — APPROVED** [review]

**Review by WouterSioen — APPROVED** [review]
So this is fully rolled out? Then I approve

**Review by rathesDot — APPROVED** [review]

**Review by tiagobastos — APPROVED** [review]

**Review by lowiebenoot — APPROVED** [review]

**Review by dcsg — APPROVED** [review]

**Pull request merged**
