### PR TITLE
Added a new return state for workOrder.download

### PR DESCRIPTION
**Pull request by nielsvermaut**

### CODE REVIEW

**Comment by tiagobastos** [comment]
Q: I think we should just add it to `Status codes`. 🤔 

I'm checking and I can't find an API response that as multiple `+ Response ...` responses in it. Maybe we just return the successful one?

**Review by Kemosabert — APPROVED** [review]

**Review by kevinwaelkens — APPROVED** [review]

**Comment by nielsvermaut** [comment]
> I'm checking and I can't find an API response that as multiple `+ Response ...` responses in it. Maybe we just return the successful one?

I feel that that would kinda render the docs flaky at best, if we'd only document the flows that are "most happy", instead of all supported flows. In my opinion, we should also document the invalid flows that are covered in our business logic, like contacts that are not found.

**Comment by tiagobastos** [comment]
> > I'm checking and I can't find an API response that as multiple `+ Response ...` responses in it. Maybe we just return the successful one?
> 
> I feel that that would kinda render the docs flaky at best, if we'd only document the flows that are "most happy", instead of all supported flows. In my opinion, we should also document the invalid flows that are covered in our business logic, like contacts that are not found.

That makes sense indeed. But we don't do it right now. So shouldn't we strive for consistency and iterate on that after?

**Review by JordyDeGroeve — APPROVED** [review]

**Comment by tiagobastos** [comment]
Also, we should compile the main apiary file

**Comment by tiagobastos** [comment]
By removing the `work-orders` branch I closed this PR without realizing 🙈 
Sorry @nielsvermaut! Any follow up we should do on it?

**Pull request closed without merging**
