### PR TITLE
Purchase order number for invoicing end points 

### PR DESCRIPTION
**Pull request by EOSullivanBerlin**
Added the documentation for the planned PO number end points.

### CODE REVIEW

**Review by Yarn-e — DISMISSED** [review]

**Review by lowiebenoot — DISMISSED** [review]
Should we add it to invoices.list as well?

**Comment by EOSullivanBerlin** [comment]
@lowiebenoot Pieter wants us to be able to filter on the PO number with the invoice.list. I can either add it now or make another PR later?

**Review by dcsg — DISMISSED** [review]

**Review by jenssegers — DISMISSED** [review]

**Comment by lowiebenoot** [comment]
Adding it to the list already makes sense to me, filtering can be added later.

**Comment by EOSullivanBerlin** [comment]
Okay I will add it.

**Review by jenssegers — APPROVED** [review]

**Review by steftrenson — COMMENTED** [review]
Since the value can also be a string, should we go with purchase_order_number or just purchase_order?

**Comment by EOSullivanBerlin** [comment]
I think number is still fine. For strings made up of Letters characters and numbers. 
1234-24343-AB I would still  call that a number for example.

**Review by lowiebenoot — APPROVED** [review]
Numbers often contain alphabetic characters, so I would just leave it like that (e.g. vat number, house number, ...)

**Review by luisaterrabrito — APPROVED** [review]

**Review by Yarn-e — APPROVED** [review]

**Pull request merged**
