### PR TITLE
Added statuses for deal phases

### PR DESCRIPTION
**Pull request by EOSullivanBerlin**
I just pass along the phases as they are in our data
base.

### CODE REVIEW

**Comment by jenssegers** [comment]
Why do you need this @EOSullivanBerlin?

**Comment by EOSullivanBerlin** [comment]
@jenssegers Pieter wants to create two areas at the bottom of the page called won and lost. He wants this because there could be up to 16 columns but sales people can move the deals to won from any stage. 
This is only possible if I can identify the won and lost phases.

**Comment by stivni** [comment]
Then again, why should we treat those areas as phases? If they are not represented as phases?
Do we have some designs or wireframes for this?

**Review by jenssegers — CHANGES_REQUESTED** [review]
I don't really agree that this is the way to go. We should try to keep deal phases independent from deal statuses.

**Comment by EOSullivanBerlin** [comment]
This is why we want to be able to identify the phases: The won and lost sections at the bottom.  
We don't have wire frames as design and UX are super busy but the idea is to complete the MVP according to what Pieter Reel and Jeroen agreed. Then with the feed back and a proper study of what the users expect we can change and modify it accordingly. 
I would therefore not expect to be able to determine now what we will need from the API in the future and I would suggest that we don't publish it and just change it as we need it.

**Pull request closed without merging**
