### PR TITLE
PRO 1866 events.list: add filter by ids

### PR DESCRIPTION
**Pull request by joaoinacio**
Add filter by id in the `events.list` endpoint, so sideloading works correctly.

E2E Tests: https://github.com/teamleadercrm/api-tests/pull/672
Implementation PR: https://github.com/teamleadercrm/core/pull/9768

### CODE REVIEW

**Review by jenssegers — DISMISSED** [review]

**Review by ArnaudWeyts — DISMISSED** [review]

**Review by adognameddog — DISMISSED** [review]

**Review by stivni — APPROVED** [review]

**Review by psrpinto — DISMISSED** [review]

**Comment by psrpinto** [comment]
We should add this to the changelog, right?

**Review by ketlane — DISMISSED** [review]

**Review by stivni — DISMISSED** [review]
don't forget to add things to the changelog

**Comment by joaoinacio** [comment]
Adding entry to changelog

**Review by psrpinto — DISMISSED** [review]

**Review by ketlane — DISMISSED** [review]

**Comment by ketlane** [comment]
No need to hold until release of profit margin, though, no?

**Review by ArnaudWeyts — DISMISSED** [review]

**Review by adognameddog — DISMISSED** [review]

**Review by jenssegers — DISMISSED** [review]

**Review by ArnaudWeyts — APPROVED** [review]

**Review by adognameddog — APPROVED** [review]

**Review by stivni — APPROVED** [review]

**Pull request merged**
