### PR TITLE
Add for_attention_of to invoices update

### PR DESCRIPTION
**Pull request by luisabritotl**

### CODE REVIEW

**Comment by stivni** [comment]
shouldn't it be part of the `.draft` too, before we add it to the `.update`?

**Comment by jdrieghe** [comment]
It's already supported by the .draft: https://github.com/teamleadercrm/core/blob/master/src/Invoicing/Domain/Invoices/DraftInvoice.php#L76
We just need to add it to the docs still. Can you make a PR for this @luisabritotl ?

**Comment by WouterSioen** [comment]
@luisabritotl I think this is already implemented? Shouldn't this get merged? (and conflicts fixed though)

**Comment by luisabritotl** [comment]
Done

**Pull request merged**
